Vagrant.configure("2") do |config|
  config.vm.define "c1" do |c1|
    c1.vm.provider :libvirt do |domain|
      domain.management_network_mac = "08-4F-A9-00-00-01"
    end
    c1.vm.box = "cisco/csr1000v"
    c1.vm.synced_folder ".", "/vagrant", disabled: true
    c1.ssh.insert_key = false
    c1.vm.boot_timeout = 180
    c1.vm.guest = :freebsd

    c1.vm.provider :libvirt do |domain|
      domain.nic_adapter_count = 8
      domain.memory = 4096
      domain.cpus = 2
      domain.driver = "kvm"
    end
    c1.vm.network :private_network,
                  :libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.1.2",
                  :libvirt__tunnel_local_port => "10002",
                  :libvirt__tunnel_ip => "127.1.3.2",
                  :libvirt__tunnel_port => "10002",
                  :libvirt__iface_name => "vgif_c1_2",
                  auto_config: false
    c1.vm.network :private_network,
                  :libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.1.3",
                  :libvirt__tunnel_local_port => "10003",
                  :libvirt__tunnel_ip => "127.1.4.1",
                  :libvirt__tunnel_port => "10001",
                  :libvirt__iface_name => "vgif_c1_3",
                  auto_config: false
  end
  config.vm.define "c2" do |c2|
    c2.vm.provider :libvirt do |domain|
      domain.management_network_mac = "08-4F-A9-00-00-02"
    end
    c2.vm.box = "arista/veos"
    c2.vm.synced_folder ".", "/vagrant", id: "vagrant-root", disabled: true
    c2.ssh.insert_key = false
    c2.ssh.shell = "bash"
    c2.vm.guest = :freebsd

    c2.vm.provider :libvirt do |domain|
      domain.disk_bus = 'ide'
      domain.cpus = 2
      domain.memory = 2048
      domain.driver = "kvm"
    end
    c2.vm.network :private_network,
                  :libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.2.1",
                  :libvirt__tunnel_local_port => "10001",
                  :libvirt__tunnel_ip => "127.1.3.3",
                  :libvirt__tunnel_port => "10003",
                  :libvirt__iface_name => "vgif_c2_1",
                  auto_config: false
    c2.vm.network :private_network,
                  :libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.2.2",
                  :libvirt__tunnel_local_port => "10002",
                  :libvirt__tunnel_ip => "127.1.4.2",
                  :libvirt__tunnel_port => "10002",
                  :libvirt__iface_name => "vgif_c2_2",
                  auto_config: false
  end
  config.vm.define "e1" do |e1|
    e1.vm.provider :libvirt do |domain|
      domain.management_network_mac = "08-4F-A9-00-00-03"
    end
    e1.vm.box = "cisco/csr1000v"
    e1.vm.synced_folder ".", "/vagrant", disabled: true
    e1.ssh.insert_key = false
    e1.vm.boot_timeout = 180
    e1.vm.guest = :freebsd

    e1.vm.provider :libvirt do |domain|
      domain.nic_adapter_count = 8
      domain.memory = 4096
      domain.cpus = 2
      domain.driver = "kvm"
    end
    e1.vm.network :private_network,
                  :libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.3.2",
                  :libvirt__tunnel_local_port => "10002",
                  :libvirt__tunnel_ip => "127.1.1.2",
                  :libvirt__tunnel_port => "10002",
                  :libvirt__iface_name => "vgif_e1_2",
                  auto_config: false
    e1.vm.network :private_network,
                  :libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.3.3",
                  :libvirt__tunnel_local_port => "10003",
                  :libvirt__tunnel_ip => "127.1.2.1",
                  :libvirt__tunnel_port => "10001",
                  :libvirt__iface_name => "vgif_e1_3",
                  auto_config: false
    e1.vm.network :private_network,
                  :libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.3.4",
                  :libvirt__tunnel_local_port => "10004",
                  :libvirt__tunnel_ip => "127.1.5.1",
                  :libvirt__tunnel_port => "10001",
                  :libvirt__iface_name => "vgif_e1_4",
                  auto_config: false
  end
  config.vm.define "e2" do |e2|
    e2.vm.provider :libvirt do |domain|
      domain.management_network_mac = "08-4F-A9-00-00-04"
    end
    e2.vm.box = "arista/veos"
    e2.vm.synced_folder ".", "/vagrant", id: "vagrant-root", disabled: true
    e2.ssh.insert_key = false
    e2.ssh.shell = "bash"
    e2.vm.guest = :freebsd

    e2.vm.provider :libvirt do |domain|
      domain.disk_bus = 'ide'
      domain.cpus = 2
      domain.memory = 2048
      domain.driver = "kvm"
    end
    e2.vm.network :private_network,
                  :libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.4.1",
                  :libvirt__tunnel_local_port => "10001",
                  :libvirt__tunnel_ip => "127.1.1.3",
                  :libvirt__tunnel_port => "10003",
                  :libvirt__iface_name => "vgif_e2_1",
                  auto_config: false
    e2.vm.network :private_network,
                  :libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.4.2",
                  :libvirt__tunnel_local_port => "10002",
                  :libvirt__tunnel_ip => "127.1.2.2",
                  :libvirt__tunnel_port => "10002",
                  :libvirt__iface_name => "vgif_e2_2",
                  auto_config: false
    e2.vm.network :private_network,
                  :libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.4.3",
                  :libvirt__tunnel_local_port => "10003",
                  :libvirt__tunnel_ip => "127.1.6.1",
                  :libvirt__tunnel_port => "10001",
                  :libvirt__iface_name => "vgif_e2_3",
                  auto_config: false
  end
  config.vm.define "x1" do |x1|
    x1.vm.provider :libvirt do |domain|
      domain.management_network_mac = "08-4F-A9-00-00-05"
    end
    x1.vm.box = "cisco/iosv"
    x1.vm.synced_folder ".", "/vagrant", disabled: true
    x1.ssh.insert_key = false
    x1.vm.boot_timeout = 180
    x1.vm.guest = :freebsd

    x1.vm.provider :libvirt do |domain|
      domain.nic_adapter_count = 8
      domain.memory = 512
      domain.cpus = 1
      domain.driver = "kvm"
      domain.nic_model_type = "e1000"
    end
    x1.vm.network :private_network,
                  :libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.5.1",
                  :libvirt__tunnel_local_port => "10001",
                  :libvirt__tunnel_ip => "127.1.3.4",
                  :libvirt__tunnel_port => "10004",
                  :libvirt__iface_name => "vgif_x1_1",
                  auto_config: false
    x1.vm.network :private_network,
                  :libvirt__network_name => "sr-mpls-bgp_7",
                  :libvirt__forward_mode => "veryisolated",
                  :libvirt__dhcp_enabled => false,
                  :libvirt__iface_name => "vgif_x1_2",
                  :auto_config => false
  end
  config.vm.define "x2" do |x2|
    x2.vm.provider :libvirt do |domain|
      domain.management_network_mac = "08-4F-A9-00-00-06"
    end
    x2.vm.box = "cisco/iosv"
    x2.vm.synced_folder ".", "/vagrant", disabled: true
    x2.ssh.insert_key = false
    x2.vm.boot_timeout = 180
    x2.vm.guest = :freebsd

    x2.vm.provider :libvirt do |domain|
      domain.nic_adapter_count = 8
      domain.memory = 512
      domain.cpus = 1
      domain.driver = "kvm"
      domain.nic_model_type = "e1000"
    end
    x2.vm.network :private_network,
                  :libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.6.1",
                  :libvirt__tunnel_local_port => "10001",
                  :libvirt__tunnel_ip => "127.1.4.3",
                  :libvirt__tunnel_port => "10003",
                  :libvirt__iface_name => "vgif_x2_1",
                  auto_config: false
    x2.vm.network :private_network,
                  :libvirt__network_name => "sr-mpls-bgp_8",
                  :libvirt__forward_mode => "veryisolated",
                  :libvirt__dhcp_enabled => false,
                  :libvirt__iface_name => "vgif_x2_2",
                  :auto_config => false
  end
end