Vagrant.configure("2") do |config|
  config.vm.define "c1" do |c1|
    c1.vm.provider :libvirt do |domain|
      domain.management_network_mac = "08-4F-A9-00-00-01"
    end
    c1.vm.box = "cisco/iosv"
    c1.vm.synced_folder ".", "/vagrant", disabled: true
    c1.ssh.insert_key = false
    c1.vm.boot_timeout = 180
    c1.vm.guest = :freebsd

    c1.vm.provider :libvirt do |domain|
      domain.nic_adapter_count = 8
      domain.memory = 512
      domain.cpus = 1
      domain.driver = "kvm"
      domain.nic_model_type = "e1000"
    end
##
    c1.vm.network :private_network,
                  :libvirt__network_name => "PVLAN",
                  :libvirt__forward_mode => "veryisolated",
                  :libvirt__dhcp_enabled => false,
                  :auto_config => false
  end
  config.vm.define "c2" do |c2|
    c2.vm.provider :libvirt do |domain|
      domain.management_network_mac = "08-4F-A9-00-00-02"
    end
    c2.vm.box = "cisco/iosv"
    c2.vm.synced_folder ".", "/vagrant", disabled: true
    c2.ssh.insert_key = false
    c2.vm.boot_timeout = 180
    c2.vm.guest = :freebsd

    c2.vm.provider :libvirt do |domain|
      domain.nic_adapter_count = 8
      domain.memory = 512
      domain.cpus = 1
      domain.driver = "kvm"
      domain.nic_model_type = "e1000"
    end
##
    c2.vm.network :private_network,
                  :libvirt__network_name => "PVLAN",
                  :libvirt__forward_mode => "veryisolated",
                  :libvirt__dhcp_enabled => false,
                  :auto_config => false
  end
  config.vm.define "c3" do |c3|
    c3.vm.provider :libvirt do |domain|
      domain.management_network_mac = "08-4F-A9-00-00-03"
    end
    c3.vm.box = "cisco/iosv"
    c3.vm.synced_folder ".", "/vagrant", disabled: true
    c3.ssh.insert_key = false
    c3.vm.boot_timeout = 180
    c3.vm.guest = :freebsd

    c3.vm.provider :libvirt do |domain|
      domain.nic_adapter_count = 8
      domain.memory = 512
      domain.cpus = 1
      domain.driver = "kvm"
      domain.nic_model_type = "e1000"
    end
##
    c3.vm.network :private_network,
                  :libvirt__network_name => "PVLAN",
                  :libvirt__forward_mode => "veryisolated",
                  :libvirt__dhcp_enabled => false,
                  :auto_config => false
  end
end