Vagrant.configure("2") do |config|
  config.vm.define "e1" do |e1|
    e1.vm.provider :libvirt do |domain|
      domain.management_network_mac = "08-4F-A9-00-00-01"
    end
    e1.vm.box = "cisco/iosv"
    e1.vm.synced_folder ".", "/vagrant", disabled: true
    e1.ssh.insert_key = false
    e1.vm.boot_timeout = 180
    e1.vm.guest = :freebsd

    e1.vm.provider :libvirt do |domain|
      domain.nic_adapter_count = 8
      domain.memory = 512
      domain.cpus = 1
      domain.driver = "kvm"
      domain.nic_model_type = "e1000"
    end
    e1.vm.network :private_network,
                  :libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.1.1",
                  :libvirt__tunnel_local_port => "10001",
                  :libvirt__tunnel_ip => "127.1.3.2",
                  :libvirt__tunnel_port => "10002",
                  :libvirt__iface_name => "vgif_e1_1",
                  auto_config: false
  end
  config.vm.define "e2" do |e2|
    e2.vm.provider :libvirt do |domain|
      domain.management_network_mac = "08-4F-A9-00-00-02"
    end
    e2.vm.box = "cisco/iosv"
    e2.vm.synced_folder ".", "/vagrant", disabled: true
    e2.ssh.insert_key = false
    e2.vm.boot_timeout = 180
    e2.vm.guest = :freebsd

    e2.vm.provider :libvirt do |domain|
      domain.nic_adapter_count = 8
      domain.memory = 512
      domain.cpus = 1
      domain.driver = "kvm"
      domain.nic_model_type = "e1000"
    end
    e2.vm.network :private_network,
                  :libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.2.1",
                  :libvirt__tunnel_local_port => "10001",
                  :libvirt__tunnel_ip => "127.1.3.3",
                  :libvirt__tunnel_port => "10003",
                  :libvirt__iface_name => "vgif_e2_1",
                  auto_config: false
  end
  config.vm.define "pe1" do |pe1|
    pe1.vm.provider :libvirt do |domain|
      domain.management_network_mac = "08-4F-A9-00-00-03"
    end
    pe1.vm.box = "cisco/csr1000v"
    pe1.vm.synced_folder ".", "/vagrant", disabled: true
    pe1.ssh.insert_key = false
    pe1.vm.boot_timeout = 180
    pe1.vm.guest = :freebsd

    pe1.vm.provider :libvirt do |domain|
      domain.nic_adapter_count = 8
      domain.memory = 4096
      domain.cpus = 2
      domain.driver = "kvm"
    end
    pe1.vm.network :private_network,
                  :libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.3.2",
                  :libvirt__tunnel_local_port => "10002",
                  :libvirt__tunnel_ip => "127.1.1.1",
                  :libvirt__tunnel_port => "10001",
                  :libvirt__iface_name => "vgif_pe1_2",
                  auto_config: false
    pe1.vm.network :private_network,
                  :libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.3.3",
                  :libvirt__tunnel_local_port => "10003",
                  :libvirt__tunnel_ip => "127.1.2.1",
                  :libvirt__tunnel_port => "10001",
                  :libvirt__iface_name => "vgif_pe1_3",
                  auto_config: false
  end
end