# Ansible inventory created from ['topology.yml', 'package:topology-defaults.yml']
#
---
all: {}
as65000:
  hosts:
    c1: {}
    c2: {}
    c3: {}
    r1: {}
    r2: {}
    r3: {}
    r4: {}
    r5: {}
    r6: {}
    r7: {}
    r8: {}
as65100:
  hosts:
    ext1: {}
as65200:
  hosts:
    ext2: {}
vsrx:
  hosts:
    c1:
      ansible_host: 192.168.121.111
      id: 11
    c2:
      ansible_host: 192.168.121.112
      id: 12
    c3:
      ansible_host: 192.168.121.113
      id: 13
    ext1:
      ansible_host: 192.168.121.121
      id: 21
    ext2:
      ansible_host: 192.168.121.122
      id: 22
    r1:
      ansible_host: 192.168.121.101
      id: 1
    r2:
      ansible_host: 192.168.121.102
      id: 2
    r3:
      ansible_host: 192.168.121.103
      id: 3
    r4:
      ansible_host: 192.168.121.104
      id: 4
    r5:
      ansible_host: 192.168.121.105
      id: 5
    r6:
      ansible_host: 192.168.121.106
      id: 6
    r7:
      ansible_host: 192.168.121.107
      id: 7
    r8:
      ansible_host: 192.168.121.108
      id: 8
