Vagrant.configure("2") do |config|
  config.vm.define "pe1" do |pe1|
    pe1.vm.provider :libvirt do |domain|
      domain.management_network_mac = "08-4F-A9-00-00-01"
    end
    pe1.vm.box = "cisco/csr1000v"
    pe1.vm.synced_folder ".", "/vagrant", disabled: true
    pe1.ssh.insert_key = false
    pe1.vm.boot_timeout = 180
    pe1.vm.guest = :freebsd

    pe1.vm.provider :libvirt do |domain|
      domain.nic_adapter_count = 8
      domain.memory = 4096
      domain.cpus = 2
      domain.driver = "kvm"
    end
    pe1.vm.network :private_network,
                  :libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.1.2",
                  :libvirt__tunnel_local_port => "10002",
                  :libvirt__tunnel_ip => "127.1.2.1",
                  :libvirt__tunnel_port => "10001",
                  :libvirt__iface_name => "vgif_pe1_2",
                  auto_config: false
    pe1.vm.network :private_network,
                  :libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.1.3",
                  :libvirt__tunnel_local_port => "10003",
                  :libvirt__tunnel_ip => "127.1.3.1",
                  :libvirt__tunnel_port => "10001",
                  :libvirt__iface_name => "vgif_pe1_3",
                  auto_config: false
  end
  config.vm.define "p1" do |p1|
    p1.vm.provider :libvirt do |domain|
      domain.management_network_mac = "08-4F-A9-00-00-02"
    end
    p1.vm.box = "cisco/iosv"
    p1.vm.synced_folder ".", "/vagrant", disabled: true
    p1.ssh.insert_key = false
    p1.vm.boot_timeout = 180
    p1.vm.guest = :freebsd

    p1.vm.provider :libvirt do |domain|
      domain.nic_adapter_count = 8
      domain.memory = 512
      domain.cpus = 1
      domain.driver = "kvm"
      domain.nic_model_type = "e1000"
    end
    p1.vm.network :private_network,
                  :libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.2.1",
                  :libvirt__tunnel_local_port => "10001",
                  :libvirt__tunnel_ip => "127.1.1.2",
                  :libvirt__tunnel_port => "10002",
                  :libvirt__iface_name => "vgif_p1_1",
                  auto_config: false
    p1.vm.network :private_network,
                  :libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.2.2",
                  :libvirt__tunnel_local_port => "10002",
                  :libvirt__tunnel_ip => "127.1.4.1",
                  :libvirt__tunnel_port => "10001",
                  :libvirt__iface_name => "vgif_p1_2",
                  auto_config: false
  end
  config.vm.define "p2" do |p2|
    p2.vm.provider :libvirt do |domain|
      domain.management_network_mac = "08-4F-A9-00-00-03"
    end
    p2.vm.box = "cisco/iosv"
    p2.vm.synced_folder ".", "/vagrant", disabled: true
    p2.ssh.insert_key = false
    p2.vm.boot_timeout = 180
    p2.vm.guest = :freebsd

    p2.vm.provider :libvirt do |domain|
      domain.nic_adapter_count = 8
      domain.memory = 512
      domain.cpus = 1
      domain.driver = "kvm"
      domain.nic_model_type = "e1000"
    end
    p2.vm.network :private_network,
                  :libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.3.1",
                  :libvirt__tunnel_local_port => "10001",
                  :libvirt__tunnel_ip => "127.1.1.3",
                  :libvirt__tunnel_port => "10003",
                  :libvirt__iface_name => "vgif_p2_1",
                  auto_config: false
    p2.vm.network :private_network,
                  :libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.3.2",
                  :libvirt__tunnel_local_port => "10002",
                  :libvirt__tunnel_ip => "127.1.4.2",
                  :libvirt__tunnel_port => "10002",
                  :libvirt__iface_name => "vgif_p2_2",
                  auto_config: false
  end
  config.vm.define "pe2" do |pe2|
    pe2.vm.provider :libvirt do |domain|
      domain.management_network_mac = "08-4F-A9-00-00-04"
    end
    pe2.vm.box = "cisco/iosv"
    pe2.vm.synced_folder ".", "/vagrant", disabled: true
    pe2.ssh.insert_key = false
    pe2.vm.boot_timeout = 180
    pe2.vm.guest = :freebsd

    pe2.vm.provider :libvirt do |domain|
      domain.nic_adapter_count = 8
      domain.memory = 512
      domain.cpus = 1
      domain.driver = "kvm"
      domain.nic_model_type = "e1000"
    end
    pe2.vm.network :private_network,
                  :libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.4.1",
                  :libvirt__tunnel_local_port => "10001",
                  :libvirt__tunnel_ip => "127.1.2.2",
                  :libvirt__tunnel_port => "10002",
                  :libvirt__iface_name => "vgif_pe2_1",
                  auto_config: false
    pe2.vm.network :private_network,
                  :libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.4.2",
                  :libvirt__tunnel_local_port => "10002",
                  :libvirt__tunnel_ip => "127.1.3.2",
                  :libvirt__tunnel_port => "10002",
                  :libvirt__iface_name => "vgif_pe2_2",
                  auto_config: false
  end
end