Vagrant.configure("2") do |config|
  config.vm.box = "cisco/iosv"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.ssh.insert_key = false
  config.vm.boot_timeout = 180
  config.vm.guest = :freebsd

  config.vm.provider :libvirt do |domain|
    domain.nic_adapter_count = 8
    domain.memory = 512
    domain.cpus = 1
    domain.driver = "kvm"
    domain.nic_model_type = "e1000"
  end

  config.vm.define "c1" do |c1|
    c1.vm.network :private_network,
                  :libvirt__network_name => "PVLAN",
                  :libvirt__forward_mode => "veryisolated",
                  :libvirt__dhcp_enabled => false,
                  :auto_config => false
    c1.vm.provider :libvirt do |domain|
      domain.management_network_mac = "08-4F-A9-00-00-01"
    end
  end

  config.vm.define "c2" do |c2|
    c2.vm.network :private_network,
                  :libvirt__network_name => "PVLAN",
                  :libvirt__forward_mode => "veryisolated",
                  :libvirt__dhcp_enabled => false,
                  :auto_config => false
    c2.vm.provider :libvirt do |domain|
      domain.management_network_mac = "08-4F-A9-00-00-02"
    end
  end

  config.vm.define "c3" do |c3|
    c3.vm.network :private_network, :libvirt__network_name => "PVLAN",
                   :libvirt__forward_mode => "veryisolated",
                   :libvirt__dhcp_enabled => false,
                   :auto_config => false
    c3.vm.provider :libvirt do |domain|
      domain.management_network_mac = "08-4F-A9-00-00-03"
    end
  end
end
