---
- name: Identify PIM interfaces on Arista EOS switches
  hosts: iosv
  gather_facts: no

  # To generate multicast - iperf -c 239.10.20.30 -B 172.16.3.8 -u -T 3 -t 20 -i 1 -b 10M

  tasks:
    - name: Configure PIM on filtered interfaces
      ios_config:
        lines:
          - ip pim sparse-mode
          - ip igmp static-group 232.10.20.10 source 172.16.0.50
          - ip igmp static-group 232.10.20.20 source 172.16.0.50
          - ip igmp static-group 232.10.20.30 source 172.16.0.50
          - ip igmp static-group 232.10.20.40 source 172.16.0.50
        parents: "interface Gi0/2"
      when: inventory_hostname in ['s5xr04', 's5xr05', 's5xr06' ]

    - name: Configure PIM on filtered interfaces
      ios_config:
        lines:
          - ip pim sparse-mode
          - ip igmp static-group 232.10.20.30 source 172.16.0.50
          - ip igmp static-group 232.10.20.20 source 172.16.0.50
          - ip igmp static-group 232.10.20.30 source 172.16.0.50
          - ip igmp static-group 232.10.20.40 source 172.16.0.50
        parents: "interface Gi0/4"
      when: inventory_hostname in ['s5xr01' ]

    - name: Configure PIM SSM default
      ios_config:
        lines:
          - ip pim ssm default
      when: "'s5x' in inventory_hostname"
