Vagrant.configure("2") do |config|
  config.vm.define "eos" do |eos|
    eos.vm.provider :libvirt do |domain|
      domain.management_network_mac = "08-4F-A9-00-00-01"
    end
    eos.vm.box = "arista/veos"
    eos.vm.synced_folder ".", "/vagrant", id: "vagrant-root", disabled: true
    eos.ssh.insert_key = false
    eos.ssh.shell = "bash"
    eos.vm.guest = :freebsd

    eos.vm.provider :libvirt do |domain|
      domain.disk_bus = 'ide'
      domain.cpus = 2
      domain.memory = 2048
      domain.driver = "kvm"
    end
    eos.vm.network :private_network,
                  :libvirt__network_name => "LAN_1",
                  :libvirt__forward_mode => "veryisolated",
                  :libvirt__dhcp_enabled => false,
                  :libvirt__iface_name => "vgif_eos_1",
                  :auto_config => false
    eos.vm.network :private_network,
                  :libvirt__network_name => "LAN_2",
                  :libvirt__forward_mode => "veryisolated",
                  :libvirt__dhcp_enabled => false,
                  :libvirt__iface_name => "vgif_eos_2",
                  :auto_config => false
  end
  config.vm.define "nxos" do |nxos|
    nxos.vm.provider :libvirt do |domain|
      domain.management_network_mac = "08-4F-A9-00-00-02"
    end
    nxos.vm.box = "cisco/nexus9300v"
    nxos.vm.synced_folder ".", "/vagrant", disabled: true
    nxos.ssh.insert_key = false
    nxos.vm.boot_timeout = 360
    nxos.vm.guest = :freebsd

    nxos.vm.provider :libvirt do |domain|
      domain.memory = 6144
      domain.cpus = 2
      domain.driver = "kvm"
    end
    nxos.vm.network :private_network,
                  :libvirt__network_name => "LAN_1",
                  :libvirt__forward_mode => "veryisolated",
                  :libvirt__dhcp_enabled => false,
                  :libvirt__iface_name => "vgif_nxos_1",
                  :auto_config => false
    nxos.vm.network :private_network,
                  :libvirt__network_name => "LAN_2",
                  :libvirt__forward_mode => "veryisolated",
                  :libvirt__dhcp_enabled => false,
                  :libvirt__iface_name => "vgif_nxos_2",
                  :auto_config => false
  end
  config.vm.define "ios" do |ios|
    ios.vm.provider :libvirt do |domain|
      domain.management_network_mac = "08-4F-A9-00-00-03"
    end
    ios.vm.box = "cisco/iosv"
    ios.vm.synced_folder ".", "/vagrant", disabled: true
    ios.ssh.insert_key = false
    ios.vm.boot_timeout = 180
    ios.vm.guest = :freebsd

    ios.vm.provider :libvirt do |domain|
      domain.nic_adapter_count = 8
      domain.memory = 512
      domain.cpus = 1
      domain.driver = "kvm"
      domain.nic_model_type = "e1000"
    end
    ios.vm.network :private_network,
                  :libvirt__network_name => "LAN_1",
                  :libvirt__forward_mode => "veryisolated",
                  :libvirt__dhcp_enabled => false,
                  :libvirt__iface_name => "vgif_ios_1",
                  :auto_config => false
    ios.vm.network :private_network,
                  :libvirt__network_name => "LAN_2",
                  :libvirt__forward_mode => "veryisolated",
                  :libvirt__dhcp_enabled => false,
                  :libvirt__iface_name => "vgif_ios_2",
                  :auto_config => false
  end
end