Vagrant.configure("2") do |config|
  config.vm.define "rtr" do |rtr|
    rtr.vm.provider :libvirt do |domain|
      domain.management_network_mac = "08-4F-A9-00-00-01"
    end
    rtr.vm.box = "cisco/csr1000v"
    rtr.vm.synced_folder ".", "/vagrant", disabled: true
    rtr.ssh.insert_key = false
    rtr.vm.boot_timeout = 180
    rtr.vm.guest = :freebsd

    rtr.vm.provider :libvirt do |domain|
      domain.nic_adapter_count = 8
      domain.memory = 4096
      domain.cpus = 2
      domain.driver = "kvm"
    end
    rtr.vm.network :private_network,
                  :libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.1.2",
                  :libvirt__tunnel_local_port => "10002",
                  :libvirt__tunnel_ip => "127.1.2.2",
                  :libvirt__tunnel_port => "10002",
                  :libvirt__iface_name => "vgif_rtr_2",
                  auto_config: false
    rtr.vm.network :private_network,
                  :libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.1.3",
                  :libvirt__tunnel_local_port => "10003",
                  :libvirt__tunnel_ip => "127.1.3.2",
                  :libvirt__tunnel_port => "10002",
                  :libvirt__iface_name => "vgif_rtr_3",
                  auto_config: false
    rtr.vm.network :private_network,
                  :libvirt__network_name => "lan-unnumbered_3",
                  :libvirt__forward_mode => "veryisolated",
                  :libvirt__dhcp_enabled => false,
                  :libvirt__iface_name => "vgif_rtr_4",
                  :auto_config => false
  end
  config.vm.define "c1" do |c1|
    c1.vm.provider :libvirt do |domain|
      domain.management_network_mac = "08-4F-A9-00-00-02"
    end
    c1.vm.box = "cisco/csr1000v"
    c1.vm.synced_folder ".", "/vagrant", disabled: true
    c1.ssh.insert_key = false
    c1.vm.boot_timeout = 180
    c1.vm.guest = :freebsd

    c1.vm.provider :libvirt do |domain|
      domain.nic_adapter_count = 8
      domain.memory = 4096
      domain.cpus = 2
      domain.driver = "kvm"
    end
    c1.vm.network :private_network,
                  :libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.2.2",
                  :libvirt__tunnel_local_port => "10002",
                  :libvirt__tunnel_ip => "127.1.1.2",
                  :libvirt__tunnel_port => "10002",
                  :libvirt__iface_name => "vgif_c1_2",
                  auto_config: false
    c1.vm.network :private_network,
                  :libvirt__network_name => "lan-unnumbered_4",
                  :libvirt__forward_mode => "veryisolated",
                  :libvirt__dhcp_enabled => false,
                  :libvirt__iface_name => "vgif_c1_3",
                  :auto_config => false
  end
  config.vm.define "c2" do |c2|
    c2.vm.provider :libvirt do |domain|
      domain.management_network_mac = "08-4F-A9-00-00-03"
    end
    c2.vm.box = "cisco/csr1000v"
    c2.vm.synced_folder ".", "/vagrant", disabled: true
    c2.ssh.insert_key = false
    c2.vm.boot_timeout = 180
    c2.vm.guest = :freebsd

    c2.vm.provider :libvirt do |domain|
      domain.nic_adapter_count = 8
      domain.memory = 4096
      domain.cpus = 2
      domain.driver = "kvm"
    end
    c2.vm.network :private_network,
                  :libvirt__tunnel_type => "udp",
                  :libvirt__tunnel_local_ip => "127.1.3.2",
                  :libvirt__tunnel_local_port => "10002",
                  :libvirt__tunnel_ip => "127.1.1.3",
                  :libvirt__tunnel_port => "10003",
                  :libvirt__iface_name => "vgif_c2_2",
                  auto_config: false
    c2.vm.network :private_network,
                  :libvirt__network_name => "lan-unnumbered_5",
                  :libvirt__forward_mode => "veryisolated",
                  :libvirt__dhcp_enabled => false,
                  :libvirt__iface_name => "vgif_c2_3",
                  :auto_config => false
  end
end