AS_65001 {
  label: AS 65001
  ca {
    label: "ca [frr]\n10.0.0.1/32"
    shape: "oval"
    style.font-size: 20
  }
  la {
    label: "la [frr]\n10.0.0.2/32"
    shape: "oval"
    style.font-size: 20
  }
  wa {
    label: "wa [frr]\n10.0.0.3/32"
    shape: "oval"
    style.font-size: 20
  }
}
AS_65002 {
  label: AS 65002
  cb {
    label: "cb [frr]\n10.0.0.4/32"
    shape: "oval"
    style.font-size: 20
  }
  lb {
    label: "lb [frr]\n10.0.0.5/32"
    shape: "oval"
    style.font-size: 20
  }
  wb {
    label: "wb [frr]\n10.0.0.6/32"
    shape: "oval"
    style.font-size: 20
  }
}
ha {
  label: "ha [linux]\n172.16.0.7/24"
}
hb {
  label: "hb [linux]\n172.16.1.8/24"
}
AS_65001.ca -- AS_65001.la {
}
AS_65001.ca -- AS_65001.wa {
}
AS_65002.cb -- AS_65002.lb {
}
AS_65002.cb -- AS_65002.wb {
}
AS_65001.la -- ha {
}
AS_65002.lb -- hb {
}
AS_65001.wa -- AS_65002.wb {
}
