AS_65000 {
  label: AS 65000
  fw {
    label: "fw [asav]\n10.0.0.1/32"
    shape: "oval"
    style.font-size: 20
  }
}
AS_65001 {
  label: AS 65001
  int {
    label: "int [frr]\n10.0.0.2/32"
    shape: "oval"
    style.font-size: 20
  }
}
AS_65100 {
  label: AS 65100
  ext {
    label: "ext [frr]\n10.0.0.3/32"
    shape: "oval"
    style.font-size: 20
  }
}
lan_1 {
  label: 172.16.0.0/24
  shape: "rectangle"
  style.border-radius: 8
  style.font-size: 20
}
h1 -> lan_1 {
}
h2 -> lan_1 {
}
AS_65001.int -> lan_1 {
}
lan_2 {
  label: 172.16.1.0/24
  shape: "rectangle"
  style.border-radius: 8
  style.font-size: 20
}
AS_65001.int -> lan_2 {
}
AS_65000.fw -> lan_2 {
}
lan_3 {
  label: 172.16.2.0/24
  shape: "rectangle"
  style.border-radius: 8
  style.font-size: 20
}
AS_65000.fw -> lan_3 {
}
AS_65100.ext -> lan_3 {
}
lan_4 {
  label: 172.16.3.0/24
  shape: "rectangle"
  style.border-radius: 8
  style.font-size: 20
}
AS_65100.ext -> lan_4 {
}
x -> lan_4 {
}
